
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  POSTGRESS_USERNAME: dWRhZ3JhbW92aWRiZGV2Cg==
  POSTGRESS_PASSWORD: U3VwZXJUYXJlMjEhISE=
  JWT_SECRET: YXNsa2pjbWtsYXNtY2xrYXNtZGNrbG1zYWRj
